### PR TITLE
added GetNonce and SetNonce following Noise revision 33 (aimed at UDP-based protocols)

### PR DESCRIPTION
**Pull request by mimoo**
Hello hello,

Following Noise revision 33, a `SetNonce()` function was added. Its behavior is pretty straight forward, still added a test that passes.

### CODE REVIEW

**Comment by titanous** [comment]
Hmm, are there use cases for this that the `Cipher()` method doesn't address? The idea I had there was to avoid exposing unsafe operations like manual nonce management explicitly as opposed to reaching into the currently safe operation of the CipherState.

**Comment by mimoo** [comment]
So for out-of-order protocols like UDP you need to explicitely send the nonce because the other peer have no other way of knowing what the nonce could be (packets are expected to drop or arrive in a different order). Because of this, Noise introduced the `SetNonce()` function in rev33, [more info here](http://noiseprotocol.org/noise.html#out-of-order-transport-messages).

I'm not sure how you could make it safer without impacting protocols that want to implement Noise on top of UDP or other out-of-order/unreliable transport layers.

**Comment by titanous** [comment]
>So I see this is as an impractical way of doing what SetNonce provides. 

Can you explain this more? I'm happy to get rid of `Cipher()` and switch to `SetNonce`/`GetNonce`, but I'd like to understand why it's better.

**Comment by mimoo** [comment]
Oh, you'd have to re-implement things via what you get with `Cipher()` in addition to track and increment nonces, whereas you could just `SetNonce`/`GetNonce` and call it a day if they were available. (It's also what the specification of Noise tell you to use.)

I'm not particularly in favor of my own PR. But I think it's not more dangerous than the current situation and is definitely simpler to use (especially since you're following the spec as a protocol builder)

**Comment by titanous** [comment]
Okay, let's do it. Please remove the `Cipher` method as there's not point in having two ways to do this.

**Comment by titanous** [comment]
Thanks!

**Comment by mimoo** [comment]
So, would it be possible to revert the removal of `Cipher()` as this is possibly something that implementations would like to have (or are already using)?

**Comment by titanous** [comment]
My inclination is to just leave one way to do this, as both implementations accomplish the same thing with a slightly different API. The main downside to the SetNonce/GetNonce version is it requires a mutex.

**Comment by rawdigits** [comment]
We actually grab the cipher state and ensure that we never reuse a nonce via a function that controls that state. I am in favor of readding `Cipher()`, because we have already created a safe nonce handler. With the SetNonce function, there is no state tracking and it is trivial to reuse a nonce and do something catastrophically bad crypto-wise.

**Comment by rawdigits** [comment]
I'd even go so far as to say that I think the way SetNonce is implemented here actually makes this library more dangerous to use than it previously was. The noise spec update isn't prescriptive on this, but until something that prevents accidental nonce reuse is added, I don't think this is a good change.

**Comment by titanous** [comment]
Yeah, given that we already have users using `Cipher`, I'm going to revert. It's not clear to me how this API is better, and after re-reading the spec I don't think it's a particularly confusing divergence.

**Comment by rawdigits** [comment]
I'm happy to implement a safe incrementing counter check version of this function at some point in the future. Our code effectively adds a single uint64 to noise.CipherState that tracks the previous nonce and requires that you always use a higher-numbered nonce on each call to Encrypt (we don't enforce it on decrypt, because that isn't a dangerous crypto operation and we catch duplicate packets elsewhere)

**Comment by titanous** [comment]
@rawdigits That'd be great!

**Pull request merged**
