### PR TITLE
Noise Pipes  implementation.

### PR DESCRIPTION
**Pull request by Scratch-net**
Added Fallback() method, XXFallback pattern and tests from github.com/rweather/noise-c

### CODE REVIEW

**Comment by Scratch-net** [comment]
@flynn did you have a chance to look at my code?

**Comment by Scratch-net** [comment]
@titanous Did you have a chance to look at my code?

**Comment by titanous** [comment]
Hey, this project is on the backburner, but I'm hoping to get to it this weekend. Thanks!

**Comment by Scratch-net** [comment]
thanks!

**Comment by titanous** [comment]
Closing. I think the best option for now is to maintain this as a separate package.

**Pull request closed without merging**
