### PR TITLE
psk mode: update for redesign

### PR DESCRIPTION
**Pull request by zx2c4**
The PSK mode has been redesigned in the latest (upcoming) revision of Noise, which WireGuard is using. This patch updates the library to use this new construction. It adds a outputs parameter to HKDF, a PresharedKeyPlacement config parameter, as well as a PSK token. This has been tested against the latest WireGuard git master, and the two are compatible.

### CODE REVIEW

**Comment by titanous** [comment]
Thanks! The implementation looks good, though the unit tests are no longer passing. The various vectors will need to be updated to match the changes.

**Comment by zx2c4** [comment]
I'm not super familiar with how you generated these. Do you want me to slog through it and figure it out, or can you do this?

**Comment by titanous** [comment]
I can take care of it, most of them were generated and then tested against another implementation, are there any other libraries that have updated to the new PSK design to test against?

**Comment by zx2c4** [comment]
Not yet. Yours is the first I did, but I'm now poking around at others.

**Comment by zx2c4** [comment]
I've updated the unit tests.

**Comment by zx2c4** [comment]
I've updated the unit tests and expanded the test vector suite as well. Everything passes. This should be merged for Tuesday's release of rev32b.

**Comment by titanous** [comment]
Thanks!

**Pull request merged**
